services:
  df-astro-dev:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
<<<<<<< HEAD
      - "4324:4324"
=======
      - "4321:4321"
>>>>>>> 04b5104 (fix: volumes attribute under services.astro-dev)
    volumes:
      - ..:/site
      - df-astro-node_modules:/site/node_modules
volumes:
  df-astro-node_modules: