services:
  df-astro-dev:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "4322:4322"
    volumes:
      - ..:/site
      - astro-node_modules:/site/node_modules
    tty: true
    stdin_open: true
    command: sleep infinity
volumes:
  df-astro-node_modules: