services:
  df-astro-dev:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "4324:4324"
    volumes:
      - ..:/site
      - df-astro-node_modules:/site/node_modules
volumes:
  df-astro-node_modules: